export const FETCH_ADDMENS_DATA_REQUEST = "FETCH_ADDMENS_DATA_FAILURE";
export const FETCH_ADDMENS_DATA_SUCCESS = "FETCH_ADDMENS_DATA_SUCCESS";
export const FETCH_ADDMENS_DATA_FAILURE = "FETCH_ADDMENS_DATA_FAILURE";

export const FETCH_CART_DATA_REQUEST = "FETCH_CART_DATA_REQUEST";
export const FETCH_CART_DATA_SUCCESS = "FETCH_CART_DATA_SUCCESS";
export const FETCH_CART_DATA_FAILURE = "FETCH_CART_DATA_FAILURE";
