export const FETCH_KIDS_DATA_REQUEST = "FETCH_KIDS_DATA_REQUEST";
export const FETCH_KIDS_DATA_SUCCESS = "FETCH_KIDS_DATA_SUCCESS";
export const FETCH_KIDS_DATA_FAILURE = "FETCH_KIDS_DATA_FAILURE";

export const FETCH_SINGLE_KIDS_REQUEST = "FETCH_SINGLE_KIDS_REQUEST";
export const FETCH_SINGLE_KIDS_SUCCESS = "FETCH_SINGLE_KIDS_SUCCESS";
export const FETCH_SINGLE_KIDS_FAILURE = "FETCH_SINGLE_KIDS_FAILURE";
