export const FETCH_WOMEN_DATA_REQUEST = "FETCH_WOMEN_DATA_REQUEST";
export const FETCH_WOMEN_DATA_SUCCESS = "FETCH_WOMEN_DATA_SUCCESS";
export const FETCH_WOMEN_DATA_FAILURE = "FETCH_WOMEN_DATA_FAILURE";

export const FETCH_SINGLE_WOMEN_REQUEST = "FETCH_SINGLE_WOMEN_REQUEST";
export const FETCH_SINGLE_WOMEN_SUCCESS = "FETCH_SINGLE_WOMEN_SUCCESS";
export const FETCH_SINGLE_WOMEN_FAILURE = "FETCH_SINGLE_WOMEN_FAILURE";
